KubernetesJob to initialize database
Element84/filmdrop-k8s-tf-modules pull request #33
Opened 2023-07-24 14:16 UTC by geomatician

This creates a new KubernetesJob that is triggered after the creation of the K8s resources for the Swoop-DB (i.e. Postgres) helm chart. The KubernetesJob initializes a new database and creates separate roles for Owner, Swoop API, Caboose, and Conductor. The database that is created has the owner role as the owner of the database. 

The KubernetesJob gets created in the same namespace (`db`) as the postgres resources and runs on a separate pod in the same namespace.

The Swoop-DB image (`quay.io/element84/swoop-db`) should be updated to contain the new Python script that was added into it (see PR: ) before testing the performance of the KubernetesJob.

2023-07-24 17:27 UTC, hectormachin requested changes

2023-07-24 21:51 UTC, hectormachin approved these changes

2023-07-25 12:09 UTC, hectormachin commented
> All the passwords here seem to be plain text, just base64 encoded. This seems strange to me, having them in here in any form at all.
> 
> Wouldn't it be better to use a random resource to generate those values, if they are not otherwise coming from an external source? That or not have any defaults at all, and require the user specify them?
> 
> @hectormachin Thoughts?

@jkeifer they are just defaults, in case no input value is passed. But it is a good point, we will look in a separate effort to minimize the default value usage for credentials.

2023-07-25 17:48 UTC, jkeifer commented on modules/jobs/dbInit.tf
> +
You might also want to add the `PGPORT`, just to be explicit about that common setting.

It also seems like these connection values likely need to come from the same vars being passed into postgres, so you might see about making them come from inputs and if there's a way to share the values from those postgres inputs (where postgres is part of the deployment) to set them.

2023-07-25 19:36 UTC, merged